#!/bin/bash
# psite-sync LOCAL SITENAME ENV
# psite-sync self pantheonname live

local="$1"
remote="$2"
instance="$3"
prefix="$HOST_PREFIX"

while test $# -gt 0; do
  case "$1" in
    -h|--help)
      echo "psite-alias"
      echo " "
      echo "psite-sync LOCAL SITENAME ENV"
      echo "psite-sync self pantheonname live"      
      echo " "
      echo "options:"
      echo "--host-prefix   host drush alias prefix (for Pantheon: \"pantheon.\", defaults to \$HOST_PREFIX)"
      echo "--no-files      do not sync the files"
      echo "-h,--help       show this screen"
      exit 0
      ;;
    --no-files)
      shift
      files=false
      shift
      ;;
    --host-prefix)
      shift
      prefix="$1"
      shift
      ;;
    *)
      break
      ;;
  esac
done


# Sync db from Pantheon site environment to local
pdrush sql-sync-pipe @${prefix}${remote}.${env} @${local} --progress


# Sync files from Pantheon site environment to local
if [ ! $files ]; then 
  pdrush -r . rsync @${prefix}${remote}.${env}:%files @${local}:%files/
fi


# Clear caches, log user in
drush @$local rr
drush @$local cc all
drush @$local uli
