#!/bin/bash
# psite-sync LOCAL SITENAME ENV
# psite-sync self pantheonname live

local="$1"
remote="$2"
env="$3"
prefix="$HOST_PREFIX"
backup_dir="$PSITE_BACKUP_DIR"

while test $# -gt 0; do
  case "$1" in
    -h|--help)
      echo "psite-alias"
      echo " "
      echo "psite-sync LOCAL SITENAME ENV"
      echo "psite-sync self pantheonname live"      
      echo " "
      echo "options:"
      echo "--host-prefix   host drush alias prefix (for Pantheon: \"pantheon.\", defaults to \$HOST_PREFIX)"
      echo "--no-files      do not sync the files"
      echo "--backup-dir    directory to save backups to (defaults to \$PSITE_BACKUP_DIR)"
      echo "-h,--help       show this screen"
      exit 0
      ;;
    --no-files)
      shift
      nofiles=false
      shift
      ;;
    --host-prefix)
      shift
      prefix="$1"
      shift
      ;;
    --)
      shift
      backup_dir=$1
      shift
      ;;
    *)
      break
      ;;
  esac
done


if [ ! -z $backup_dir ]; then
  echo "Taking backup of local database..."  
  drush @${local} sql-dump --gzip --result-file=$backup_dir/backup_${local}_$(date +"%Y-%m-%d").sql
fi


echo "Syncing db from Pantheon site environment to local..."
drush -y sql-sync-pipe @${prefix}${remote}.${env} @${local} --progress


if [ ! $nofiles ]; then 
  echo "Syncing files from Pantheon site environment to local..."  
  drush -r . rsync @${prefix}${remote}.${env}:%files/ @${local}:%files --progress
fi


echo "Clearing caches, logging in as uid=0..."
drush @$local rr
drush @$local cc all
drush @$local uli
